language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - rabbitmq

env:
  matrix:
    - NETTE=nette-2.4-dev
    - NETTE=nette-2.4
    - NETTE=nette-2.3

matrix:
  include:
    - php: 5.6
      env: NETTE=nette-2.3 COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"
  exclude:
    - php: 5.4
      env: NETTE=nette-2.4-dev
    - php: 5.4
      env: NETTE=nette-2.4
    - php: 5.5
      env: NETTE=nette-2.4-dev
    - php: 5.5
      env: NETTE=nette-2.4
  allow_failures:
    - php: hhvm

before_install:
  - travis_retry composer self-update
  - wget -O /tmp/composer-nette https://raw.githubusercontent.com/Kdyby/TesterExtras/master/bin/composer-nette.php
  - php /tmp/composer-nette

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_EXTRA_ARGS
  - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint
  - travis_retry composer create-project --no-interaction nette/code-checker /tmp/code-checker ~2.5

script:
  - vendor/bin/tester -s -p php -c ./tests/php.ini-unix ./tests/KdybyTests/
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - php /tmp/code-checker/src/code-checker.php --short-arrays

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
