language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - rabbitmq

env:
  matrix:
    - NETTE=nette-2.4

matrix:
  include:
    - php: 7.1
      env: NETTE=nette-2.4 COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"
    - php: 7.3
      env: NETTE=nette-2.4 COVERAGE="--coverage ./coverage.xml --coverage-src ./src" TESTER_RUNTIME="phpdbg"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_EXTRA_ARGS
  - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint
  - travis_retry composer create-project --no-interaction kdyby/code-checker /tmp/code-checker
  - travis_retry wget -O /tmp/coveralls.phar https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar

script:
  - vendor/bin/tester $COVERAGE -s -p ${TESTER_RUNTIME:-php} -c ./tests/php.ini-unix ./tests/KdybyTests/
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - php /tmp/code-checker/src/code-checker.php --short-arrays

after_script:
  - if [ "$COVERAGE" != "" ]; then php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true; fi

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
