language: php

sudo: false

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.6
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - dist: precise
      php: 5.3
      env:
        - SYMFONY_VERSION=2.7.*
        - INCREASE_MEMORY=yes
    - dist: precise
      php: 5.3
      env:
        - SYMFONY_VERSION=2.8.*
        - INCREASE_MEMORY=yes

    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest --prefer-stable"

    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1
      env: SYMFONY_VERSION=4.3.*
    - php: 7.1
      env: DEPENDENCIES=beta
    - php: 7.2
      env: DEPENDENCIES=beta
    - php: 7.3
      env: SYMFONY_VERSION=4.3.*
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*

  allow_failures:
    - php: nightly

env:
  global:
    - SYMFONY_VERSION=""

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available";
  - if [ "$INCREASE_MEMORY" = "yes" ]; then echo "memory_limit = 2048M" > travis.php.ini && phpenv config-add travis.php.ini; fi;
  - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle "$SYMFONY_VERSION"; fi
  - if [ "$COMPOSER_FLAGS" != "" ]; then composer update --prefer-dist --no-interaction --no-scripts $COMPOSER_FLAGS; fi;

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit
