language: php

sudo: false

env:
  matrix:
    - NETTE=nette-2.3-dev COMPOSER_EXTRA_ARGS=""
    - NETTE=nette-2.3 COMPOSER_EXTRA_ARGS=""
    - NETTE=nette-2.3 COMPOSER_EXTRA_ARGS="--prefer-lowest"

services:
  - rabbitmq

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - composer self-update

install:
  - mkdir -p vendor/bin
  - wget -O vendor/bin/composer-nette https://raw.githubusercontent.com/Kdyby/TesterExtras/master/bin/composer-nette.php
  - php vendor/bin/composer-nette
  - composer update --no-interaction --prefer-source $COMPOSER_EXTRA_ARGS

before_script:
  - composer create-project --prefer-source --no-interaction jakub-onderka/php-parallel-lint vendor/php-parallel-lint ~0.8
  - php vendor/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - composer create-project --prefer-source --no-interaction nette/code-checker vendor/code-checker ~2.2
  - php vendor/code-checker/src/code-checker.php -d src
  - php vendor/code-checker/src/code-checker.php -d tests

script: vendor/bin/tester -s -p php -c ./tests/php.ini-unix ./tests/KdybyTests/

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
